# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  pngdecoder_config = debug
  test_config = debug

else ifeq ($(config),release)
  pngdecoder_config = release
  test_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := pngdecoder test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

pngdecoder:
ifneq (,$(pngdecoder_config))
	@echo "==== Building pngdecoder ($(pngdecoder_config)) ===="
	@${MAKE} --no-print-directory -C pngdecoder -f Makefile config=$(pngdecoder_config)
endif

test:
ifneq (,$(test_config))
	@echo "==== Building test ($(test_config)) ===="
	@${MAKE} --no-print-directory -C test -f Makefile config=$(test_config)
endif

clean:
	@${MAKE} --no-print-directory -C pngdecoder -f Makefile clean
	@${MAKE} --no-print-directory -C test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   pngdecoder"
	@echo "   test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"